"""Pre-receipt instruction register: every instruction introduced in this session, in order of introduction.

Sources (verbatim captures in ../session_instructions/):
  U1 initial user message (with attachments, incl. the main prompt MP); MP main prompt (attached with U1,
  executed after the reconciliation per I022); A1 assistant clarification request; U2 dry-reproduction
  instruction; U3 consolidation instruction; R standing rules applied by the agent in this session.
loc: U* -> paragraph indices (blank-line split); MP -> section headings (verbatim lines).
"""
CATEGORIES = ["scientific", "technical", "reproducibility-related", "data-security-related",
              "publication/interpretation-related"]
S, T, R, D, P = CATEGORIES

MP_SECTIONS = ["PROJECT TITLE", "SESSION STATUS", "ACTUAL TOMMO PROJECT", "ACTUAL EXPECTED DATA DISTRIBUTION",
               "APPROVED GENE UNIVERSE", "NO GWAS ASSUMPTION", "ACTUAL MEDICATION DATA STRUCTURE",
               "TWO-WAVE DESIGN IS CENTRAL", "PRIMARY OUTCOME RECONSTRUCTION", "DOSE CHANGE", "MEDICATION CHANGE",
               "FORMULATION INFORMATION", "FOOD / FFQ DATA ARE ACTUALLY AVAILABLE", "CHEMOSENSORY CROSS-DOMAIN MODULE",
               "LIFESTYLE COVARIATES", "LABORATORY AND PHYSIOLOGICAL DATA", "CLAIMS DATA", "CENTRAL SCIENTIFIC STORY",
               "CHEMICAL-SURVEILLANCE INTERPRETATION", "PRE-RECEIPT HYPOTHESIS HIERARCHY",
               "PRIMARY MEDICATION-CHANGE ENDPOINTS", "IMPORTANT CHANGE FROM EARLIER PLAN", "PRIMARY STATISTICAL MODELS",
               "GENE-LEVEL AND VARIANT-LEVEL ANALYSIS", "MULTIPLE TESTING", "MACHINE LEARNING", "EXPLORATORY GWAS",
               "PRE-RECEIPT CODE PACKAGE", "SYNTHETIC DATA", "PRE-RECEIPT TIMESTAMP PACKAGE", "REGISTRATION / TIMESTAMP",
               "PUBLIC / REGISTERABLE CONTENT", "DATA RECEIPT EVENT", "FINAL MANUSCRIPT STORY", "IMPORTANT CAUSAL BOUNDARY",
               "NATURE-LEVEL SUCCESS CONDITION", "FINAL PRE-RECEIPT OUTPUTS", "FINAL GATE", "STOP",
               "POST-RECEIPT OFFLINE VALIDATION"]

d = "docs/"
# (id, source, loc, primary_category, extra_categories, scientifically_consequential, summary, deliverables, evidence)
REGISTER = [
    ("I001", "U1", "0-1", T, [R], "N", "Check all four attachments (application, research plan, dataset workbook, legacy handoff ZIP) first",
     [d + "22_RESTRICTED_SOURCE_HASH_INDEX.md"], "tommoデータセット.xlsx"),
    ("I002", "U1", "2-6", S, [], "Y", "Not a redesign session; the legacy ZIP is the formal pre-ToMMo scientific history",
     [d + "01_APPROVED_PROTOCOL_SCOPE.md", d + "04_GATE_HISTORY_AND_LOCKS.md"], "formal pre-ToMMo scientific history"),
    ("I003", "U1", "7-9", S, [], "Y", "Approved research plan and application are the highest-priority constraint",
     [d + "01_APPROVED_PROTOCOL_SCOPE.md"], "highest-priority scientific constraint"),
    ("I004", "U1", "10-12", S, [], "Y", "Actual distribution scope = dataset workbook + taste-related SNP information in the plan",
     [d + "02_ACTUAL_DISTRIBUTION_SCOPE.md"], "Selected file families"),
    ("I005", "U1", "13-17", S, [], "Y", "Reconcile approved plan / distribution / legacy freeze in PROTOCOL_DISTRIBUTION_FREEZE_RECONCILIATION.md first",
     ["../PROTOCOL_DISTRIBUTION_FREEZE_RECONCILIATION.md"], "分類表（全118項目）"),
    ("I006", "U1", "18-20", S, [], "Y", "Classify every legacy analysis/prediction/control/gradient/calibration/SAP item into exactly one of seven labels",
     ["../reconciliation/RECONCILIATION_CLASSIFICATION.csv"], "REQUIRES PROTOCOL AMENDMENT"),
    ("I007", "U1", "21-22", S, [], "Y", "Legacy frozen items keep their pre-specification status unless they contradict plan or distribution",
     [d + "04_GATE_HISTORY_AND_LOCKS.md"], "Locks carried forward"),
    ("I008", "U1", "23-28", S, [], "Y", "Out-of-scope legacy items: do not run, delete or replace; record UNTESTABLE or REQUIRES PROTOCOL AMENDMENT",
     [d + "AMENDMENT_LOG.md", d + "05_SNP_ANALYSIS_HIERARCHY.csv"], "retained, not analysed, not deleted"),
    ("I009", "U1", "29-30", D, [S], "Y", "Legacy OPEN PRIMARY DATA WITH RESTRICTIONS is a historical gate decision, not authorization",
     [d + "04_GATE_HISTORY_AND_LOCKS.md", d + "16_PRE_POST_RECEIPT_DECISION_BOUNDARY.md"], "does NOT authorize participant-level analysis"),
    ("I010", "U1", "31-33", R, [D], "Y", "Order: old freeze -> reconciliation -> final pre-receipt freeze -> independent timestamp -> receipt -> offline validation",
     [d + "04_GATE_HISTORY_AND_LOCKS.md"], "old freeze → protocol/data reconciliation → final pre-receipt freeze → independent timestamp → ToMMo data receipt → offline validation"),
    ("I011", "U1", "34-37", R, [S], "Y", "Freeze theory, hypotheses, SNP hierarchy, endpoint, controls, gradient, calibration, multiple testing, interpretation, boundaries, offline code; third-party-verifiable timestamp package",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md", d + "FINAL_PRE_RECEIPT_PROTOCOL.md"], "third-party verification"),
    ("I012", "U1", "38", D, [], "Y", "Do not analyse participant-level ToMMo data yet",
     [d + "16_PRE_POST_RECEIPT_DECISION_BOUNDARY.md", d + "COMPLETENESS_AUDIT.md"], "Participant-level ToMMo data were not received, inspected or analysed"),
    ("I013", "U1", "39-41", S, [], "Y", "Primary phenotype = longitudinal ph1->ph2 medication change (dose change, active-ingredient change, within-class switch, addition, removal), not current use",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md"], "LONGITUDINAL MEDICATION CHANGE"),
    ("I014", "U1", "42", S, [], "Y", "FFQ ph1/ph2 = secondary triangulation of pre-specified chemosensory phenotypes",
     [d + "09_CHEMOSENSORY_FFQ_LOCK.csv", d + "13_MULTIPLE_TESTING_FINAL.md"], "secondary-triangulation"),
    ("I015", "U1", "43", T, [S], "Y", "Prefer Drug ID / KEDD ID; free text for brand/formulation/route completion and QC",
     [d + "08_DRUG_CLASS_MAPPING_RULES.md", "offline_pipeline/config/drug_dictionary.yaml"], "Identification hierarchy"),
    ("I016", "U1", "44", S, [D], "Y", "Claims data are not a primary-analysis premise until confirmed in the delivered files",
     [d + "02_ACTUAL_DISTRIBUTION_SCOPE.md"], "NO CLAIMS DATA IN THE PRIMARY DISTRIBUTION"),
    ("I017", "U1", "45-48", P, [S], "Y", "Maintain the central research arc (genetic + acquired chemosensory plasticity -> modifiable component -> future precision-medicine direction)",
     [d + "25_MANUSCRIPT_ARCHITECTURE.md", d + "03_THEORY_TO_PROTOCOL_MAP.csv"], "Chemosensory phenotype has genetic and acquired components"),
    ("I018", "U1", "49-51", P, [], "Y", "Strictly separate what ToMMo can show from future hypotheses (plasticity, food education/conditioning, response modification, economic, global-health benefit)",
     [d + "27_FUTURE_INTERVENTION_MODEL.md", d + "28_HEALTH_ECONOMIC_GLOBAL_HEALTH_MODEL.md"], "not tested in ToMMo"),
    ("I019", "U1", "52", P, [], "Y", "Do not conclude untested intervention effects from ToMMo",
     [d + "27_FUTURE_INTERVENTION_MODEL.md", d + "25_MANUSCRIPT_ARCHITECTURE.md"], "no intervention efficacy is concluded"),
    ("I020", "U1", "53-55", P, [S], "Y", "ToMMo analysis = population-level foundation test of whether the chemosensory system predicts drug-related individual differences",
     [d + "21_PUBLIC_REGISTRATION_SUMMARY.md"], "tests only the population-level genetic part"),
    ("I021", "U1", "56", R, [S], "Y", "No new scientific analysis proposals until the reconciliation is complete",
     [d + "04_GATE_HISTORY_AND_LOCKS.md"], "completed and committed before any new pre-receipt analytic decision"),
    ("I022", "U1", "57", T, [], "N", "Then execute the attached main prompt",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md"], "executing the main prompt after the reconciliation"),
    ("I023", "MP", "SESSION STATUS", R, [], "Y", "Preserve chronology THEORY -> DRY EVIDENCE -> PREDICTION FREEZE -> GATES -> FINAL PRE-RECEIPT FREEZE -> INDEPENDENT TIMESTAMP -> RECEIPT -> OFFLINE VALIDATION -> MANUSCRIPT",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md"], "THEORY → DRY EVIDENCE → PREDICTION FREEZE"),
    ("I024", "MP", "SESSION STATUS", R, [D], "Y", "Complete and time-stamp the entire scientific and statistical plan before receipt or inspection of participant-level data",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md"], "before receipt or inspection of any participant-level ToMMo data"),
    ("I025", "MP", "PROJECT TITLE;ACTUAL TOMMO PROJECT", P, [S], "Y", "Approved title; broader receptor biology background is compatible but immune mediation is not tested",
     [d + "01_APPROVED_PROTOCOL_SCOPE.md"], "immune mediation is NOT directly tested"),
    ("I026", "MP", "ACTUAL EXPECTED DATA DISTRIBUTION", S, [], "Y", "Expected distribution: release 3.1.1 families; no metabolomics, claims, long-term claims or WGS",
     [d + "02_ACTUAL_DISTRIBUTION_SCOPE.md"], "No metabolomics"),
    ("I027", "MP", "ACTUAL EXPECTED DATA DISTRIBUTION", S, [], "Y", "SNP data delivered as the taste-related SNP dataset unless the manifest says otherwise",
     [d + "02_ACTUAL_DISTRIBUTION_SCOPE.md"], "SNP delivery"),
    ("I028", "MP", "APPROVED GENE UNIVERSE", S, [], "Y", "Approved 20-gene universe",
     [d + "05_SNP_ANALYSIS_HIERARCHY.csv", "offline_pipeline/config/snp_map.yaml"], "OTOP1"),
    ("I029", "MP", "APPROVED GENE UNIVERSE", S, [], "Y", "Take the SNP list only from the delivered manifest; never invent availability or assume a dry-frozen SNP is delivered",
     [d + "02_ACTUAL_DISTRIBUTION_SCOPE.md"], "SNP availability is not invented"),
    ("I030", "MP", "APPROVED GENE UNIVERSE", S, [], "Y", "At receipt assign each prediction: directly testable / pre-specified proxy / gene-level secondary only / untestable",
     [d + "05_SNP_ANALYSIS_HIERARCHY.csv"], "TESTABLE WITH PRE-SPECIFIED PROXY"),
    ("I031", "MP", "APPROVED GENE UNIVERSE", S, [], "Y", "No substitution of more favorable SNPs after outcome inspection",
     [d + "24_AMENDMENT_POLICY.md"], "no favorable SNP substitution"),
    ("I032", "MP", "NO GWAS ASSUMPTION", S, [], "Y", "No GWAS in the confirmatory plan; exploratory only if genome-wide data delivered and authorized",
     [d + "14_CONFIRMATORY_SAP_PRE_RECEIPT.md"], "GWAS (confirmatory or otherwise"),
    ("I033", "MP", "ACTUAL MEDICATION DATA STRUCTURE", T, [S], "Y", "Medication structure (45 slots, IDs, text, duration, frequency, dose); normalization hierarchy PRIMARY IDs / SECONDARY structured fields / TERTIARY free text",
     [d + "02_ACTUAL_DISTRIBUTION_SCOPE.md", "offline_pipeline/config/variable_map.yaml"], "Normalization hierarchy"),
    ("I034", "MP", "ACTUAL MEDICATION DATA STRUCTURE", T, [], "Y", "Do not use NLP as the primary identification method when structured IDs exist",
     [d + "08_DRUG_CLASS_MAPPING_RULES.md"], "NLP/free-text parsing is never the primary method"),
    ("I035", "MP", "TWO-WAVE DESIGN IS CENTRAL", S, [], "Y", "Exploit the two-wave design; construct change phenotypes across waves",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md"], "participants with the medication section answered at both waves"),
    ("I036", "MP", "TWO-WAVE DESIGN IS CENTRAL", P, [], "Y", "Neutral terminology; no 'discontinuation due to intolerance' or 'switch due to taste'",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md"], "Terminology (neutral, data-derived)"),
    ("I037", "MP", "PRIMARY OUTCOME RECONSTRUCTION", S, [], "Y", "Reconstruct the protocol surrogate outcomes (dose change, medication change, switch, addition, deletion)",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md"], "dose change, medication change, switch, addition, deletion"),
    ("I038", "MP", "PRIMARY OUTCOME RECONSTRUCTION", S, [], "Y", "Pre-specify algorithms (brand vs ingredient, combinations, duplicates, units, frequency, missing phase, unknown IDs)",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md", d + "07_DOSE_HARMONIZATION_RULES.md"], "Endpoint algorithms"),
    ("I039", "MP", "PRIMARY OUTCOME RECONSTRUCTION", R, [], "Y", "Synthetic tests for every algorithm case",
     [d + "17_SYNTHETIC_PIPELINE_VALIDATION.md"], "Fixed edge cases"),
    ("I040", "MP", "DOSE CHANGE", S, [], "Y", "Derive dose per administration, administrations/day, daily dose; standardized daily dose change primary; no unsafe or cross-formulation harmonization",
     [d + "07_DOSE_HARMONIZATION_RULES.md"], "Primary dose quantity"),
    ("I041", "MP", "MEDICATION CHANGE", S, [T], "Y", "Deterministic medication-change algorithm; IDs first; offline licensed class database with frozen version",
     [d + "08_DRUG_CLASS_MAPPING_RULES.md", "../data/raw_atc_20261004/LEDGER.csv"], "Classification database"),
    ("I042", "MP", "FORMULATION INFORMATION", S, [], "Y", "Formulation module conditional confirmatory; genotype-blind validation after receipt; if unreliable MECHANISTIC GRADIENT NOT TESTABLE without invalidating primary",
     [d + "11_FORMULATION_MODULE_FREEZE.md"], "MECHANISTIC GRADIENT NOT TESTABLE"),
    ("I043", "MP", "FOOD / FFQ DATA ARE ACTUALLY AVAILABLE", S, [], "Y", "FFQ = secondary triangulation; no redesign after seeing data",
     [d + "09_CHEMOSENSORY_FFQ_LOCK.csv"], "F01"),
    ("I044", "MP", "CHEMOSENSORY CROSS-DOMAIN MODULE", S, [], "Y", "Pre-specify restricted FFQ phenotypes with rationale, direction, gene, status and family (CHEMOSENSORY_FFQ_LOCK)",
     [d + "09_CHEMOSENSORY_FFQ_LOCK.csv", "offline_pipeline/config/ffq_lock.yaml"], "biological_rationale"),
    ("I045", "MP", "LIFESTYLE COVARIATES", S, [], "Y", "Lifestyle variables as confounders / pre-specified parallel exposures / sensitivity, not outcomes",
     [d + "14_CONFIRMATORY_SAP_PRE_RECEIPT.md"], "Lifestyle variables are confounders"),
    ("I046", "MP", "LABORATORY AND PHYSIOLOGICAL DATA", S, [], "Y", "Laboratory/physiological data for confounding, disease definition, characterization; no broad lab phenome scan",
     [d + "14_CONFIRMATORY_SAP_PRE_RECEIPT.md"], "no laboratory phenome scan"),
    ("I047", "MP", "CLAIMS DATA", S, [D], "Y", "Assume no claims; later claims only via data-availability amendment; not needed for the primary manuscript",
     [d + "24_AMENDMENT_POLICY.md", d + "02_ACTUAL_DISTRIBUTION_SCOPE.md"], "Data-availability"),
    ("I048", "MP", "CENTRAL SCIENTIFIC STORY", P, [S], "Y", "Central story S = f(G, E), M = g(S, D); motivates, does not prove, intervention",
     [d + "03_THEORY_TO_PROTOCOL_MAP.csv"], "S = f(G, E)"),
    ("I049", "MP", "CHEMICAL-SURVEILLANCE INTERPRETATION", P, [], "Y", "Chemical-surveillance claim classes; no immune causation claim",
     [d + "25_MANUSCRIPT_ARCHITECTURE.md"], "Indirect: chemical-surveillance biology"),
    ("I050", "MP", "PRE-RECEIPT HYPOTHESIS HIERARCHY", S, [], "Y", "Primary, secondary 1-4 and negative-control hypotheses (frozen, testable only)",
     [d + "14_CONFIRMATORY_SAP_PRE_RECEIPT.md"], "SECONDARY 4"),
    ("I051", "MP", "PRIMARY MEDICATION-CHANGE ENDPOINTS", S, [], "Y", "Seven longitudinal endpoints with exact algorithms and synthetic examples; never defined after seeing frequencies",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md"], "WITHIN_CLASS_SWITCH"),
    ("I052", "MP", "IMPORTANT CHANGE FROM EARLIER PLAN", S, [], "Y", "Primary is no longer current use; current exposure = secondary cross-sectional",
     [d + "06_MEDICATION_LONGITUDINAL_ENDPOINT_FREEZE.md", d + "AMENDMENT_LOG.md"], "Current/recent medication exposure is a secondary cross-sectional analysis only"),
    ("I053", "MP", "PRIMARY STATISTICAL MODELS", S, [], "Y", "Logistic models with G + covariates; drug-specific with indication restriction; dose models; no p-value-driven model selection",
     [d + "14_CONFIRMATORY_SAP_PRE_RECEIPT.md"], "no p-value-driven model selection"),
    ("I054", "MP", "GENE-LEVEL AND VARIANT-LEVEL ANALYSIS", S, [], "Y", "Level A (frozen variants) vs Level B (gene-constrained); no promotion of novel SNPs",
     [d + "13_MULTIPLE_TESTING_FINAL.md", d + "05_SNP_ANALYSIS_HIERARCHY.csv"], "a novel Level-B SNP cannot be promoted to confirmatory"),
    ("I055", "MP", "MULTIPLE TESTING", S, [], "Y", "Freeze testing families and corrections",
     [d + "13_MULTIPLE_TESTING_FINAL.md"], "Holm, α = 0.05"),
    ("I056", "MP", "MACHINE LEARNING", S, [], "Y", "ML secondary only; nested CV; clinical vs clinical+genotype; delta-AUC and calibration with CI; no causal SHAP",
     [d + "15_ML_SECONDARY_PLAN.md"], "Nested cross-validation"),
    ("I057", "MP", "EXPLORATORY GWAS", S, [], "Y", "Exploratory GWAS only if delivered/authorized and after confirmatory analyses are locked",
     [d + "14_CONFIRMATORY_SAP_PRE_RECEIPT.md"], "exploratory amendment is filed after confirmatory results are locked"),
    ("I058", "MP", "PRE-RECEIPT CODE PACKAGE", T, [R], "Y", "Offline code package with modules 01-22",
     ["offline_pipeline/run_pipeline.py"], "22_privacy_safe_export"),
    ("I059", "MP", "PRE-RECEIPT CODE PACKAGE", T, [R], "Y", "Five centralized configs; delivered column names never hard-coded",
     ["offline_pipeline/config/variable_map.yaml", "offline_pipeline/tests/test_pipeline.py"], "Every analysis script reads column names ONLY through this file"),
    ("I060", "MP", "SYNTHETIC DATA", R, [], "Y", "Synthetic PH1/PH2 data with all listed fields and edge cases; run the entire pipeline before receipt",
     [d + "17_SYNTHETIC_PIPELINE_VALIDATION.md", "synthetic_validation/RUN_LEDGER.json"], "Synthetic data mimic the delivered structure"),
    ("I061", "MP", "PRE-RECEIPT TIMESTAMP PACKAGE", R, [], "Y", "Timestamp ZIP with theory, mapping, gates, SNP hierarchy, endpoints, FFQ, controls, SAP, hierarchy, calibration, formulation, interpretation, code, tests, environment, manifest, checksums",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md", d + "18_PRE_RECEIPT_MANIFEST.csv"], "CHEMOSENSORY_TOMMO_PRE_RECEIPT_FREEZE_"),
    ("I062", "MP", "PRE-RECEIPT TIMESTAMP PACKAGE", D, [R], "Y", "Package completed before data receipt or inspection",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md"], "No participant-level ToMMo data were received"),
    ("I063", "MP", "REGISTRATION / TIMESTAMP;PUBLIC / REGISTERABLE CONTENT", D, [P], "Y", "Separate public vs restricted content; restricted sources only as hash index",
     [d + "20_REGISTRATION_CONTENT_PLAN.md", d + "22_RESTRICTED_SOURCE_HASH_INDEX.md"], "Restricted layer (never redistributed)"),
    ("I064", "MP", "PUBLIC / REGISTERABLE CONTENT", P, [], "Y", "Registration content (hypotheses ... success/refutation criteria, amendment policy, timestamp evidence)",
     [d + "20_REGISTRATION_CONTENT_PLAN.md", d + "21_PUBLIC_REGISTRATION_SUMMARY.md"], "Registration fields"),
    ("I065", "MP", "DATA RECEIPT EVENT", D, [R], "Y", "At receipt: timestamp, hashes, offline storage, only QC checks before documented sign-off",
     [d + "23_DATA_RECEIPT_EVENT_LOG_TEMPLATE.md"], "No association model may run"),
    ("I066", "MP", "FINAL MANUSCRIPT STORY", P, [], "Y", "Nine-step manuscript story",
     [d + "25_MANUSCRIPT_ARCHITECTURE.md"], "Predictions were frozen before population data"),
    ("I067", "MP", "IMPORTANT CAUSAL BOUNDARY", P, [], "Y", "Causal boundary: no immune, plasticity, intervention, economic claims",
     [d + "25_MANUSCRIPT_ARCHITECTURE.md"], "Not tested: immune causation"),
    ("I068", "MP", "NATURE-LEVEL SUCCESS CONDITION", P, [], "Y", "High-impact success conditions",
     [d + "26_NATURE_SUCCESS_CRITERIA.md"], "Negative controls behave"),
    ("I069", "MP", "FINAL PRE-RECEIPT OUTPUTS", T, [], "N", "Produce documents 01-29 plus the complete offline source code",
     [d + "18_PRE_RECEIPT_MANIFEST.csv"], "29_FINAL_PRE_RECEIPT_HANDOFF.md"),
    ("I070", "MP", "FINAL GATE", R, [S], "Y", "Assign READY / READY WITH TECHNICAL ITEMS ONLY / NOT READY; READY only if all scientific choices frozen",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md"], "Final gate"),
    ("I071", "MP", "STOP;POST-RECEIPT OFFLINE VALIDATION", T, [D], "Y", "Stop after the package; no waiting for data; next session executes the frozen analysis",
     [d + "29_FINAL_PRE_RECEIPT_HANDOFF.md"], "must execute the frozen analysis rather than redesign it"),
    ("I072", "U2", "0", R, [], "Y", "Independently rerun reproducible dry-analysis components from source data/search outputs",
     ["../DRY_REPRODUCTION_AUDIT.md", "../dry_reproduction/run_dry_reproduction_audit.py"], "## K. 再実行方法"),
    ("I073", "U2", "0", R, [S], "Y", "Verify locked predictions, evidence scores, negative controls and gate conclusions regenerate without participant data",
     ["../DRY_REPRODUCTION_AUDIT.md"], "## E. 参加者レベルデータの除外"),
    ("I074", "U2", "0", R, [], "Y", "Record discrepancies in DRY_REPRODUCTION_AUDIT.md",
     ["../DRY_REPRODUCTION_AUDIT.md"], "## G. 不一致一覧"),
    ("I075", "U3", "0", R, [], "Y", "Consolidate all pre-receipt instructions into final protocol, decision log, amendment log and timestamp package",
     [d + "FINAL_PRE_RECEIPT_PROTOCOL.md", d + "DECISION_LOG.md", d + "AMENDMENT_LOG.md"], "All pre-receipt instructions of the session are consolidated here"),
    ("I076", "U3", "1", R, [], "Y", "Preserve chronology of introduction; classify each instruction into five categories",
     [d + "INSTRUCTION_REGISTER.csv"], "publication/interpretation-related"),
    ("I077", "U3", "2", R, [], "Y", "No scientifically consequential instruction may remain only in chat history",
     [d + "COMPLETENESS_AUDIT.md"], "scientifically consequential"),
    ("I078", "U3", "3", R, [], "Y", "Completeness check against the full session history before finalizing",
     [d + "COMPLETENESS_AUDIT.md"], "Result:"),
    ("R01", "R", "standing rule", R, [], "Y", "Persist public/raw data with machine-readable ledger; never overwrite; mark incomplete retrievals",
     ["../data/raw_atc_20261004/LEDGER.csv", "../data/raw_ensembl_20261004_attempt1_incomplete/INCOMPLETE.txt"], "sha256"),
    ("R02", "R", "standing rule", D, [], "Y", "Never publish third-party record-level raw data or restricted documents",
     [d + "20_REGISTRATION_CONTENT_PLAN.md"], "third-party record-level raw downloads"),
    ("R03", "R", "standing rule", R, [], "Y", "Stable explicit seeds; deterministic reruns in fresh processes",
     ["offline_pipeline/config/analysis_config.yaml", "synthetic_validation/RUN_LEDGER.json"], "seed: 42"),
    ("R04", "R", "standing rule", P, [], "N", "Manuscript numbers injected from generated outputs; no repository paths or editing history in manuscript text",
     [d + "25_MANUSCRIPT_ARCHITECTURE.md"], "numbers injected from generated result files"),
]

EVENTS = [
    ("E01", "A1", "Assistant asked which protocol version (attached = 2026-03-13 text vs 2026-06-13 revision) is approved; no answer at freeze time",
     [d + "DECISION_LOG.md", d + "01_APPROVED_PROTOCOL_SCOPE.md"], "2026-06-13 revision"),
]

ORDER = {"U1": 1, "MP": 2, "U2": 3, "A1": 4, "U3": 5, "R": 6}
INTRODUCED = {
    "U1": "message 1 (session start, 2026-10-04 ~18:08 UTC)",
    "MP": "attached to message 1; executed after I005 completed (I022)",
    "A1": "assistant message after message 2",
    "U2": "message 2",
    "U3": "message 3",
    "R": "standing rules active throughout the session",
}
