#!/usr/bin/env python3
"""Curate study-level evidence into the numbered deliverable CSVs.

Each record cites a PMID; citation metadata is pulled from the verified
search pool / anchor XML (titles, journals, years, DOIs come from PubMed,
never hand-typed). Extracted fields (N, effect, P) are transcribed from the
abstracts; fields not stated in the abstract are left empty and flagged
abstract_only=True.
"""
import xml.etree.ElementTree as ET
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
pool = pd.read_csv(ROOT / "evidence" / "search_pool.csv")
meta = pool.set_index(pool.pmid.astype(int))

def cite(pmid):
    pmid = int(pmid)
    if pmid in meta.index:
        r = meta.loc[pmid]
        return {"pmid": pmid, "citation": f"{r.authors.split(';')[0].split(' ')[0]} et al." if ";" in str(r.authors) else r.authors,
                "title": r.title, "journal": r.journal, "year": r.year, "doi": r.doi}
    return {"pmid": pmid, "citation": "?", "title": "?", "journal": "?", "year": "?", "doi": "?"}

# ---------- 04_VARIANT_EVIDENCE (1B + 1D genotype->sensory) ----------
VARIANT = [
 dict(gene="TAS2R38", variant="PAV vs AVI diplotype (A49P,V262A,I296V)", rsid="rs713598;rs1726866;rs10246939",
      stimulus="PTC/PROP", phenotype_kind="detection threshold + suprathreshold intensity",
      n="pedigree+families", effect="PAV detects/strong bitterness; AVI null", pval="<1e-10 (linkage+assoc)",
      replication="replicated worldwide; defining study", functional="in vitro PAV-responsive, AVI null",
      design="positional cloning + psychophysics + functional assay", tier="A", pmid=12595690,
      layer="1B", note="establishes G->S1 architecture; PTC/PROP are drug-adjacent thiourea ligands"),
 dict(gene="TAS2R38", variant="5 coding haplotypes", rsid="rs713598;rs1726866;rs10246939",
      stimulus="PTC and PROP", phenotype_kind="perceived intensity",
      n="~60", effect="in vitro receptor response correlates with individual perception",
      pval="<0.05 (correlations)", replication="functional mechanistic confirmation",
      functional="five haplotypes = operatively distinct receptors", design="psychophysics + heterologous expression",
      tier="A", pmid=15723792, layer="1B", note="genotype->receptor->perception closed loop"),
 dict(gene="TAS2R38", variant="A49P", rsid="rs713598", stimulus="PROP",
      phenotype_kind="bitter intensity; sweet preference", n="143 children + mothers",
      effect="P allele -> higher PROP bitterness; children P-carriers prefer sweeter sucrose",
      pval="<0.05", replication="replicated (pediatric extension)", functional="A49P known functional",
      design="cross-sectional genotype + psychophysics", tier="A", pmid=15687429, layer="1B",
      note="pediatric genotype->S1"),
 dict(gene="TAS2R38", variant="A49P etc.", rsid="rs713598", stimulus="PROP",
      phenotype_kind="bitter intensity", n="Sardinian isolate cohort",
      effect="association of PTC/PROP sensitivity with TAS2R38 haplotype", pval="<0.05",
      replication="independent isolate replication", functional="", design="isolate cohort",
      tier="A", pmid=15466815, layer="1B", note=""),
 dict(gene="TAS2R38", variant="PAV/AVI + rare haplotypes", rsid="rs713598;rs1726866;rs10246939",
      stimulus="PTC, PROP, goitrin, methimazole, sinigrin", phenotype_kind="detection threshold",
      n="56", effect="continuous allele-function range; PAV/AVI significant; rare haplotypes no phenotypic assoc",
      pval="SNP P<0.002; haplotype P<0.001", replication="functional + phenotypic",
      functional="EC50 PROP 2.1uM, PTC 1.1uM (PAV); AVI null", design="sequencing + assay + threshold",
      tier="A", pmid=23632915, layer="1B", note="methimazole = drug ligand of TAS2R38"),
 dict(gene="TAS2R38", variant="diplotypes", rsid="rs713598 etc.", stimulus="PROP",
      phenotype_kind="bitterness (taster class)", n="large twin cohort",
      effect="rs713598 P=1.6e-104, 45.9% of trait variance", pval="1.6e-104",
      replication="GWAS-level + replication", functional="", design="GWAS in 1457 twins",
      tier="A", pmid=20675712, layer="1B", note="same GWAS: quinine -> chr12 TAS2R19 cluster rs10772420 P=1.8e-15 (5.8% var); caffeine/SOA no hit"),
 dict(gene="TAS2R38", variant="diplotype", rsid="", stimulus="goitrin (crucifer toxin, PROP analog)",
      phenotype_kind="detection threshold", n="50",
      effect="goitrin threshold correlates with PROP/PTC thresholds (rs=0.46); PAV EC50 65uM, AVI no response",
      pval="8.9e-4 (PROP), 7.5e-4 (PTC)", replication="", functional="PAV vs AVI dose-response",
      design="psychophysics + functional assay", tier="A", pmid=20551074, layer="1B",
      note="H2 support: drug-like ligand generalization"),
 dict(gene="TAS2R38", variant="A49P", rsid="rs713598", stimulus="PROP",
      phenotype_kind="bitter intensity", n="adults, age-stratified",
      effect="genotype-phenotype relationship modified by age", pval="<0.05",
      replication="", functional="", design="cross-sectional", tier="A", pmid=20594349,
      layer="1B", note="moderation by age; relevant to adult plasticity interpretation"),
 dict(gene="TAS2R38", variant="haplotype", rsid="", stimulus="PTC",
      phenotype_kind="bitter sensitivity", n="worldwide panels",
      effect="independent convergent evolution of taster alleles in humans and chimps",
      pval="", replication="", functional="", design="comparative genetics", tier="A",
      pmid=16612383, layer="1H", note="evolutionary: ancient functional variation"),
 dict(gene="TAS2R38", variant="PTC locus haplotypes", rsid="", stimulus="PTC",
      phenotype_kind="taster/nontaster", n="global populations",
      effect="balancing selection signature; ancient polymorphism maintained",
      pval="", replication="", functional="", design="population genetics", tier="A",
      pmid=14997422, layer="1H", note="evolutionary depth of the key locus"),
 dict(gene="TAS2R family", variant="151 coding haplotypes across 24 genes", rsid="",
      stimulus="—", phenotype_kind="coding diversity", n="55 worldwide",
      effect="elevated amino-acid diversity (Ka/Ks 0.94), FST 0.22", pval="pi=0.11% p<0.01; FST p<0.05",
      replication="", functional="", design="resequencing", tier="A", pmid=16086309,
      layer="1H/1B", note="broad functional variation substrate"),
 dict(gene="TAS2R family", variant="loss-of-function and pseudogene alleles", rsid="",
      stimulus="—", phenotype_kind="relaxed constraint", n="25 genes",
      effect="relaxed selective constraint; segregating LoF", pval="",
      replication="", functional="", design="evolutionary analysis", tier="A", pmid=15367488,
      layer="1H", note=""),
 dict(gene="TAS2R19", variant="R299C", rsid="rs10772420", stimulus="quinine",
      phenotype_kind="perceived intensity", n="1457 twins + replication",
      effect="common variant explains 5.8% of quinine intensity variance", pval="1.8e-15; rep p=1e-5",
      replication="independent twin replication", functional="", design="GWAS", tier="A",
      pmid=20675712, layer="1B", note="drug-like alkaloid stimulus (quinine is itself a drug)"),
 dict(gene="TAS2R31", variant="allelic variants", rsid="", stimulus="quinine",
      phenotype_kind="bitterness; grapefruit liking", n="",
      effect="TAS2R31 variants associate with quinine bitterness and grapefruit liking", pval="<0.05",
      replication="", functional="", design="candidate assoc", tier="A", pmid=26024668,
      layer="1B", note=""),
 dict(gene="TAS2R31/TAS2R43", variant="polymorphisms", rsid="", stimulus="acesulfame-K (non-nutritive sweetener)",
      phenotype_kind="bitterness", n="", effect="Ace-K bitterness varies with TAS2R31/43 variants",
      pval="<0.05", replication="", functional="", design="candidate assoc", tier="A",
      pmid=23599216, layer="1B", note="non-food-adjacent synthetic compound"),
 dict(gene="TAS2R38", variant="rs713598", rsid="rs713598", stimulus="chloramphenicol (antibiotic)",
      phenotype_kind="suprathreshold bitterness (gLMS)", n="143",
      effect="TAS2R38 diplotype associates with chloramphenicol bitterness", pval="<0.05",
      replication="single cohort", functional="", design="genotype + sensory panel",
      tier="A", pmid=35967977, layer="1D", note="DIRECT drug-S1 association"),
 dict(gene="TAS2R9", variant="V187A", rsid="", stimulus="ofloxacin (antibiotic)",
      phenotype_kind="suprathreshold bitterness (gLMS)", n="143",
      effect="TAS2R9 V187A associates with ofloxacin bitterness", pval="<0.05",
      replication="single cohort", functional="", design="genotype + sensory panel", tier="A",
      pmid=35967977, layer="1D", note="DIRECT drug-S1 association; receptor matches BitterDB ofloxacin->TAS2R9"),
 dict(gene="TAS1R1/TAS1R3", variant="TAS1R1-372T/A; TAS1R3-757C/R", rsid="",
      stimulus="MSG / MSG+IMP (umami)", phenotype_kind="recognition threshold",
      n="", effect="thresholds track in vitro variant dose-response", pval="<0.05",
      replication="", functional="heterologous expression", design="genotype + threshold + assay",
      tier="A", pmid=19696921, layer="1B", note="non-bitter modality: G->S1 generalizes beyond TAS2R"),
 dict(gene="TAS1R2", variant="rs12033832", rsid="rs12033832", stimulus="sucrose",
      phenotype_kind="threshold + suprathreshold + intake", n="696; subset n=95",
      effect="genotype-BMI interaction on sensitivity and sugar intake", pval="0.01 (sens), 0.003 (intake)",
      replication="single cohort", functional="", design="candidate assoc", tier="A",
      pmid=26279452, layer="1B", note=""),
 dict(gene="TAS1R3", variant="promoter polymorphism", rsid="", stimulus="sweet tastants",
      phenotype_kind="taste sensitivity", n="", effect="TAS1R3 promoter allele associates with sweet sensitivity",
      pval="<0.05", replication="", functional="", design="candidate assoc", tier="A",
      pmid=19559618, layer="1B", note=""),
 dict(gene="SCNN1B", variant="rs239345; rs3785368", rsid="rs239345;rs3785368", stimulus="NaCl",
      phenotype_kind="suprathreshold salt intensity", n="95",
      effect="AA (rs239345) and TT (rs3785368) perceive salt less intensely", pval="0.02; 0.03",
      replication="single cohort", functional="", design="candidate assoc", tier="C",
      pmid=23118204, layer="1B", note="TRPV1 rs8065080 also associated (P=0.008)"),
 dict(gene="SCNN1A", variant="A663T", rsid="", stimulus="NaCl",
      phenotype_kind="salty taste recognition threshold", n="207",
      effect="threshold-zinc interaction only in AA homozygous women; no main genotype effect on preference",
      pval="0.02 (interaction)", replication="single cohort", functional="", design="candidate assoc",
      tier="C", pmid=24317554, layer="1B", note="weak/conditional evidence for ENaC"),
 dict(gene="CA6 (gustin)", variant="rs2274333", rsid="rs2274333", stimulus="—",
      phenotype_kind="fungiform papilla density", n="",
      effect="gustin variant associated with papilla density (indirect sensory mechanism)",
      pval="<0.05", replication="", functional="", design="candidate assoc", tier="D",
      pmid=25447475, layer="1B", note="non-receptor confounder pathway"),
 dict(gene="TAS2R38", variant="diplotype", rsid="", stimulus="PROP",
      phenotype_kind="bitterness vs mRNA expression", n="",
      effect="perception correlates with receptor mRNA expression in taste cells",
      pval="<0.05", replication="", functional="", design="expression assoc", tier="B",
      pmid=24025627, layer="1B", note="expression-level mechanism beyond coding variants"),
 dict(gene="TAS2R38", variant="diplotype", rsid="rs713598",
      stimulus="chromium picolinate? no—bitter stimuli battery", phenotype_kind="multiple bitter sensations",
      n="", effect="diplotype explains part but not all of PROP supertasting",
      pval="", replication="", functional="", design="psychophysics", tier="A",
      pmid=18209019, layer="NEG", note="supertasting depends on more than TAS2R38"),
 dict(gene="TAS2R38", variant="haplotype", rsid="", stimulus="salt (dietary sodium behavior)",
      phenotype_kind="24h urinary Na excretion", n="42",
      effect="PAV/PAV predicts lower urinary Na (b=-1780.6); no genotype effect on salt sensitivity",
      pval="0.036", replication="single small cohort", functional="",
      design="cross-sectional + biomarker", tier="A", pmid=32453275, layer="1B/NEG",
      note="behaviorally relevant marker, but sensitivity null"),
 dict(gene="TAS2R38", variant="A49P", rsid="rs713598",
      stimulus="clindamycin liquid (pediatric antibiotic)", phenotype_kind="palatability rating; facial distaste",
      n="67 children", effect="NO association of TAS2R38 or TRPA1 variants with clindamycin liking/side effects",
      pval="ns", replication="null direct test", functional="", design="prospective cohort + genotyping",
      tier="A", pmid=42162282, layer="1D/NEG", note="KEY NULL: genotype->drug sensory null for a non-TAS2R38 ligand"),
 dict(gene="TRPA1", variant="rs11988795", rsid="rs11988795",
      stimulus="pediatric ibuprofen formulation", phenotype_kind="tingling/chemesthesis",
      n="trained adult panel", effect="TRPA1 variant associated with tingling sensation, independent of ancestry",
      pval="<5e-8 (GWAS-level reported)", replication="single cohort discovery", functional="",
      design="GWAS + sensory panel", tier="D", pmid=37685855, layer="1D",
      note="chemesthesis channel, not taste receptor; supports G->S1_drug generalization beyond TAS2R"),
 dict(gene="TAS2R4", variant="—", rsid="", stimulus="PROP (in TAS2R38 AVI carriers)",
      phenotype_kind="bitter perception rescue", n="",
      effect="differential TAS2R4 activation may restore PROP tasting in some AVI individuals",
      pval="", replication="", functional="heterologous assay", design="functional + sensory", tier="A",
      pmid=38732607, layer="1B", note="redundancy complicates genotype->phenotype mapping"),
 dict(gene="TAS2R2", variant="functional variant in some populations", rsid="",
      stimulus="phenylbutazone etc.", phenotype_kind="receptor activation",
      n="", effect="TAS2R2 (former pseudogene) responds to 8/122 compounds incl. drug phenylbutazone",
      pval="", replication="", functional="heterologous assay", design="screening",
      tier="A", pmid=36929150, layer="1C/1D", note="population-dependent receptor functionality"),
 dict(gene="TAS2R38", variant="PAV haplotype", rsid="", stimulus="tobacco (real-world bitter exposure)",
      phenotype_kind="smoking behavior", n="237 + 1353 + 2363 + 4973",
      effect="PTC tasters less common among smokers (71.5% vs 82.5%, P=0.03); genotype trend ns in larger cohorts",
      pval="0.03 small cohort; ns replication", replication="inconsistent", functional="",
      design="multi-cohort assoc", tier="A", pmid=27711175, layer="NEG",
      note="weak/inconsistent S1->behavior translation in adults"),
]

# ---------- 05_DRUG_SENSORY_EVIDENCE (1C; rows=claims, BitterDB edges appended separately) ----------
DRUG = [
 dict(drug="104 natural/synthetic bitter compounds", receptor="25 hTAS2Rs",
      evidence_grade="B", finding="receptive-range map: 3 receptors detect ~50%; 19 compounds hit up to 15 receptors",
      ec50="", system="heterologous HEK", species="human", pmid=20022913,
      note="foundational matrix; includes some drugs"),
 dict(drug="chloroquine, haloperidol, erythromycin, procainamide, ofloxacin", receptor="T2Rs (multiple)",
      evidence_grade="B/C", finding="pharmaceuticals activate extraoral+oral T2Rs; off-target hypothesis",
      system="review+assay data", species="human/mouse", pmid=22964302, note="hypothesis-framing paper with assay citations"),
 dict(drug="erythromycin(T2R10), ofloxacin(T2R9), dapsone, colchicine, carisoprodol(T2R14), diphenidol",
      receptor="multiple TAS2Rs", evidence_grade="B",
      finding="agonists suppress LPS cytokine release in human lung macrophages (extraoral functional)",
      system="primary human cells", species="human", pmid=31632299, note="extraoral competing pathway (1G)"),
 dict(drug="quinine", receptor="T2R4/7/10/39/46", evidence_grade="B",
      finding="quinine increases T2R surface expression ~2x (pharmacochaperone)", system="heterologous cells",
      species="human", pmid=27223611, note="drug modifies receptor beyond agonism"),
 dict(drug="chloramphenicol + ofloxacin", receptor="human panel", evidence_grade="A",
      finding="dominant sensation bitterness (~moderate gLMS); genotype-linked variation",
      system="human sensory panel n=143", species="human", pmid=35967977, note=""),
 dict(drug="ibuprofen pediatric formulation", receptor="human panel", evidence_grade="A",
      finding="wide individual variation in taste/chemesthesis; TRPA1 rs11988795 -> tingling; ancestry differences",
      system="GWAS sensory panel", species="human", pmid=37685855, note=""),
 dict(drug="clindamycin liquid", receptor="human pediatric cohort", evidence_grade="A",
      finding="54% disliked taste; variation not explained by TAS2R38/TRPA1", system="prospective cohort n=67",
      species="human", pmid=42162282, note="negative for candidate genes"),
 dict(drug="prednisolone powder", receptor="human+sensor", evidence_grade="A",
      finding="commercial prednisolone powder intensely bitter; masking methods quantified",
      system="human + taste sensor", species="human", pmid=18827377, note=""),
 dict(drug="amlodipine ODT (10 products)", receptor="human gustatory sensation test", evidence_grade="A",
      finding="large inter-product palatability differences for same API", system="human panel",
      species="human", pmid=23927469, note="formulation dominates API taste"),
 dict(drug="25+ APIs", receptor="electronic tongue", evidence_grade="D",
      finding="taste sensor quantifies bitterness/masking of pharmaceuticals", system="taste sensor",
      species="instrument", pmid=15365669, note="instrument grade"),
 dict(drug="denatonium, chloroquine, thiamine, noscapine", receptor="TAS2R4/10; TAS2R3/10",
      evidence_grade="C", finding="drugs relax guinea-pig trachea (functional, non-oral)",
      system="isolated tissue", species="guinea pig", pmid=22962016, note=""),
 dict(drug="phenylbutazone + 7 compounds", receptor="TAS2R2", evidence_grade="B",
      finding="TAS2R2 responds to phenylbutazone uniquely among TAS2Rs", system="heterologous",
      species="human", pmid=36929150, note=""),
 dict(drug="caffeine bitterness", receptor="TAS2R7/43 blockade by (R)-citronellal", evidence_grade="B",
      finding="odorant antagonist attenuates caffeine bitterness via TAS2R43", system="heterologous+human",
      species="human", pmid=27569025, note="masking mechanism"),
 dict(drug="PTU (propylthiouracil) + ZINC hits", receptor="TAS2R38 on L-cells", evidence_grade="B",
      finding="PTU activates enteroendocrine TAS2R38 -> GLP-1 release (extraoral drug action)",
      system="HuTu-80 cells", species="human cell line", pmid=27208775, note="extraoral drug efficacy"),
 dict(drug="berberine", receptor="enteroendocrine T2R", evidence_grade="B",
      finding="berberine activates bitter taste responses in STC-1 cells", system="cell line",
      species="mouse", pmid=29363059, note=""),
 dict(drug="flufenamic acid (BitterDB-guided)", receptor="BitterDB + cell stiffness", evidence_grade="B",
      finding="database-driven identification of potent TAS2R agonist drug", system="screening",
      species="human cells", pmid=38389834, note=""),
 dict(drug="nuciferine", receptor="intestinal TAS2R46", evidence_grade="C",
      finding="intestinal TAS2R46 mediates metabolic effects", system="mouse", species="mouse",
      pmid=40311594, note=""),
]

# ---------- 06_PLASTICITY_EVIDENCE (1F) ----------
PLASTICITY = [
 dict(intervention="long-term dietary sodium reduction", population="adults", n="~20", design="longitudinal intervention",
      outcome="preferred salt level declined; salt taste adapted over months", effect="preference shift toward lower salt",
      pval="significant (classic)", persistence="months", reversibility="",
      pmid=7148734, note="classic plasticity evidence; small n"),
 dict(intervention="increasing dietary salt", population="adults", n="", design="dietary manipulation",
      outcome="salt taste preference shifted up with higher intake", effect="preference shift", pval="<0.05",
      persistence="", reversibility="yes (bidirectional)", pmid=3797487, note=""),
 dict(intervention="short-term diet change", population="adults", n="", design="short-term intervention",
      outcome="salt taste preference responds to diet", effect="", pval="", persistence="",
      reversibility="", pmid=1562204, note=""),
 dict(intervention="experimental sodium depletion", population="adults", n="", design="controlled depletion",
      outcome="altered salt taste in normal volunteers", effect="", pval="", persistence="",
      reversibility="", pmid=2185626, note="physiological modulation of salt taste"),
 dict(intervention="reduced simple-sugar diet (3 months)", population="adults", n="", design="dietary RCT",
      outcome="perceived sweet intensity increased; pleasantness unchanged", effect="sensitivity shift without hedonic shift",
      pval="<0.05", persistence="", reversibility="", pmid=26607941,
      note="plasticity is perceptual, not hedonic"),
 dict(intervention="6-month low/regular/high sweet exposure", population="180 adults", n="180",
      design="parallel RCT (Sweet Tooth)", outcome="sweet liking/intake outcomes", effect="",
      pval="", persistence="4-mo follow-up", reversibility="", pmid=41485871,
      note="large modern RCT; see results in text"),
 dict(intervention="repeated taste exposure (vegetables)", population="low-income children", n="",
      design="longitudinal exposure", outcome="increased liking", effect="acceptance up", pval="<0.05",
      persistence="", reversibility="", pmid=20541572, note="pediatric, not adult"),
 dict(intervention="repeated exposure to disliked Nordic bars", population="adults", n="",
      design="controlled exposure", outcome="acceptance increased with exposure", effect="", pval="",
      persistence="", reversibility="", pmid=21868139, note="adult food-exposure effect"),
 dict(intervention="repeated exposure to reduced-energy-dense food", population="adults", n="",
      design="controlled exposure", outcome="increased liking", effect="", pval="", persistence="",
      reversibility="", pmid=20375191, note=""),
 dict(intervention="repeated taste exposure (longitudinal)", population="adults", n="", design="longitudinal",
      outcome="practice effects on taste acceptance", effect="", pval="", persistence="", reversibility="",
      pmid=18585415, note=""),
 dict(intervention="capsaicin repeated low-dose oral rinsing (17d)", population="51 adults", n="51",
      design="controlled desensitization", outcome="reduced oral burn (desensitization)", effect="S1 down",
      pval="", persistence="", reversibility="partial", pmid=38135109,
      note="chemesthesis plasticity; receptor-adjacent"),
 dict(intervention="repeated capsaicin in real food", population="adults", n="", design="dietary",
      outcome="minimal sensitization", effect="null-ish", pval="", persistence="", reversibility="",
      pmid=40876703, note="NEGATIVE: limited plasticity in real-world format"),
 dict(intervention="oral NaCl rinsing without consumption (2wk)", population="42 adults", n="42",
      design="cross-over intervention", outcome="no change in salt DT/RT/suprathreshold", effect="NULL",
      pval=">0.05 all", persistence="", reversibility="", pmid=36894246,
      note="KEY NEGATIVE: taste exposure alone insufficient; consumption context matters"),
 dict(intervention="8-wk low-sodium cereal", population="39 children", n="39", design="RCT",
      outcome="acceptance increased but taste preferences and thresholds unchanged", effect="hedonic shift, no S1 shift",
      pval="ns (preference/threshold)", persistence="", reversibility="", pmid=31006818,
      note="mixed: liking plastic, sensory threshold not"),
 dict(intervention="bitter/sour novel foods x10 exposures", population="20 adults", n="20",
      design="controlled exposure", outcome="NO change in pleasantness for bitter/sour; sweet/salty improved",
      effect="null for bitter", pval="ns", persistence="", reversibility="", pmid=7878095,
      note="NEGATIVE: bitter specifically resistant to exposure-driven liking in adults"),
 dict(intervention="herb/spice seasoning of low-salt soup", population="adults", n="", design="consumer test",
      outcome="increased liking of low-salt soup over repeated exposure", effect="", pval="",
      persistence="", reversibility="", pmid=24879887, note="compensation strategy"),
 dict(intervention="salt-reduced reformulation (products)", population="consumers", n="50 studies",
      design="systematic review + meta-analysis", outcome="up to ~40% (bread)/~70% (meat) reduction without acceptability loss",
      effect="", pval="ns acceptability change", persistence="", reversibility="", pmid=26745848,
      note="masking-by-matrix, not perceiver plasticity"),
]

# ---------- 1E sensory->behavior ----------
BEHAV = [
 dict(drug="liquid medications (any)", population="children 3-10y", n=448, sensory="TAS2R38 bitter-sensitive genotype",
      behavior="solid formulation usage history", effect="bitter-sensitive children more likely to have used solid formulations",
      pval="<0.05", design="retrospective pooled", confounders="age, indication", pmid=22440514,
      note="genotype->S2 proxy; pediatric only"),
 dict(drug="liquid medications", population="children 3-10y + mothers", n=172, sensory="TAS2R38 A49P",
      behavior="reported rejection of liquid medication", effect="P-allele carriers more likely to report rejecting liquids (chi2=5.72)",
      pval="0.02", design="retrospective interview", confounders="recall, indication", pmid=26391354,
      note=""),
 dict(drug="pediatric antibiotics (review)", population="children", n="", sensory="taste/palatability of formulations",
      behavior="adherence", effect="taste/palatability affect adherence to antibiotics", pval="",
      design="narrative review", confounders="indication, severity", pmid=22088684,
      note="established pediatric link"),
 dict(drug="clindamycin liquid", population="children 1st prescription", n=67, sensory="dislike of taste (54%)",
      behavior="adherence + side effects (36%)", effect="substantial individual variability; taste linked to behavioral responses",
      pval="<0.001 distaste expressions", design="prospective cohort", confounders="", pmid=42162282,
      note="S1->S2 proximate but genotype null"),
 dict(drug="poor-tasting pediatric medicines (scoping)", population="children", n="", sensory="taste acceptability",
      behavior="acceptability/adherence impact", effect="documented impact across medicines", pval="",
      design="scoping review", confounders="", pmid=40837710, note=""),
 dict(drug="sucrose masking of bitter agents (urea, caffeine, denatonium, PROP, quinine)",
      population="children+adults", n="", sensory="sucrose suppresses bitterness",
      behavior="improved acceptance", effect="sucrose reduces bitterness moderate->weak (adults); TAS1R3-sensitive report more reduction",
      pval="<0.05", design="controlled psychophysics", confounders="", pmid=25381313,
      note="formulation lever; genotype interaction suggested"),
 dict(drug="psychiatric medications", population="adults", n="", sensory="tablet shape/size/color",
      behavior="adherence", effect="physical form influences adherence", pval="",
      design="review/survey", confounders="", pmid=42391492, note="adult evidence is form not flavor"),
 dict(drug="alcohol/caffeine", population="20 adults", n=20, sensory="ethanol detection threshold",
      behavior="alcohol intake", effect="intake correlates with threshold + pharmacological reactivity (23% var)",
      pval="", design="cross-sectional", confounders="personality", pmid=7878095, note="adult S1->consumption (non-medication)"),
 dict(drug="brassica vegetables", population="Danish DCH cohort n=500", n=500, sensory="TAS2R38 haplotype",
      behavior="brassica intake", effect="NULL association", pval="ns", design="cohort",
      confounders="diet context", pmid=21338274, note="NEGATIVE: genotype does not predict real-world intake"),
 dict(drug="diet patterns", population="adults", n="", sensory="PROP sensitivity",
      behavior="dietary pattern, BMI", effect="NULL", pval="ns", design="cross-sectional",
      confounders="", pmid=17659901, note="NEGATIVE"),
 dict(drug="smoking", population="multi-cohort", n=8626, sensory="PTC/TAS2R38",
      behavior="smoking status", effect="small-cohort assoc, larger cohorts ns", pval="0.03/ns",
      design="multi-cohort", confounders="", pmid=27711175, note="weak translation"),
]

# ---------- 1G extraoral (competing mechanism) ----------
EXTRAORAL = [
 dict(tissue="airway smooth muscle", finding="TAS2R activation -> bronchodilation via localized Ca2+",
      species="human+mouse", pmid=20972434, note="established extraoral drug action"),
 dict(tissue="lung macrophages", finding="TAS2R agonists (incl. erythromycin, ofloxacin, dapsone, colchicine, carisoprodol) suppress cytokine release",
      species="human cells", pmid=31632299, note="immunomodulatory off-target pathway"),
 dict(tissue="enteroendocrine L-cells", finding="TAS2R38 activation by PTU -> GLP-1 release", species="human cell line",
      pmid=27208775, note="drug can act via gut T2R, bypassing perception"),
 dict(tissue="gut enteroendocrine", finding="taste signaling elements regulate nutrient-responsive secretion",
      species="human", pmid=19571229, note=""),
 dict(tissue="sinonasal SCC", finding="TAS2R + solitary chemosensory cells drive innate immunity", species="human",
      pmid=31231752, note=""),
 dict(tissue="testis", finding="functional T2Rs in mammalian testis", species="mouse/human",
      pmid=22983952, note=""),
 dict(tissue="arteries", finding="bitter agonists induce vasorelaxation (porcine coronary)", species="pig",
      pmid=40693268, note=""),
]

# ---------- 1H evolution ----------
EVOL = [
 dict(claim="balancing selection at PTC locus maintained taster/nontaster polymorphism", pmid=14997422),
 dict(claim="independent evolution of bitter sensitivity humans vs chimps", pmid=16612383),
 dict(claim="relaxed constraint + segregating LoF across TAS2R repertoire", pmid=15367488),
 dict(claim="unusually high coding diversity of TAS2R genes worldwide", pmid=16086309),
 dict(claim="TAS2R38 present/functionally variable in Neanderthals", pmid=19675003),
 dict(claim="African PTC diversity: functionally diverse alleles under selection", pmid=22130969),
 dict(claim="TAS2R16 salicin allele selection history", pmid=24177185),
 dict(claim="gustation as ancient vertebrate chemical-detection system (sweet T1R origin)", pmid=41618601),
 dict(claim="T2R gene evolution deep roots (coelacanth/zebrafish receptors)", pmid=33355666),
 dict(claim="T2Rs function as bitter taste receptors (discovery)", pmid=10761935),
 dict(claim="novel family of mammalian taste receptors (T2R cloning)", pmid=10761934),
]

def emit(rows, out):
    df = pd.DataFrame([{**cite(r.pop("pmid")), **r} for r in rows])
    df.to_csv(ROOT / out, index=False)
    print(out, len(df))
    return df

emit([dict(r) for r in VARIANT], "04_VARIANT_EVIDENCE.csv")
emit([dict(r) for r in DRUG], "05_DRUG_SENSORY_EVIDENCE.csv")
emit([dict(r) for r in PLASTICITY], "06_PLASTICITY_EVIDENCE.csv")
emit([dict(r) for r in BEHAV], "evidence/sensory_behavior_evidence.csv")
emit([dict(r) for r in EXTRAORAL], "evidence/extraoral_evidence.csv")
emit([dict(r) for r in EVOL], "evidence/evolution_evidence.csv")

# 03_STUDY_INVENTORY = union of cited PMIDs
allp = sorted({r["pmid"] for r in VARIANT+DRUG+PLASTICITY+BEHAV+EXTRAORAL+EVOL})
inv = pool[pool.pmid.astype(int).isin(allp)][["pmid","title","journal","year","authors","doi"]].copy()
inv = inv.drop_duplicates("pmid").sort_values("year")
layer_map = {}
for rows_, ln in [(VARIANT,"1B/1D"),(DRUG,"1C"),(PLASTICITY,"1F"),(BEHAV,"1E"),(EXTRAORAL,"1G"),(EVOL,"1H")]:
    for r in rows_:
        layer_map.setdefault(int(r["pmid"]), set()).add(ln)
inv["layers"] = inv.pmid.map(lambda p: ";".join(sorted(layer_map.get(int(p), set()))))
inv.to_csv(ROOT / "03_STUDY_INVENTORY.csv", index=False)
print("inventory:", len(inv))
